### ISSUE TITLE
Option to exclude asset hash details

### ISSUE THREAD

**Issue by henrist** [hupe1980/jest-cdk-snapshot#5]
When creating a snapshot of a stack containing a Lambda Function, without using inline code, the `S3Bucket` and `S3Key`, as well as the parameters they are pointing to, will change every time the asset changes. In addition, when having CDK handle versioning of lambdas, by `lambda.Function.currentVersion`, the resource created will include the asset hash.

This makes it less convenient to create test snapshots of such stacks.

Would you accept a contribution to add an option to modify these values so that they will not change between snapshots even when the asset hashes changes?

I've done something similar in my https://github.com/henrist/cdk-snapshot package (for creating a "snapshot" of the whole app), where the parameters are simply dropped, and the references to them is modified to replace the asset hash.

**Comment by hupe1980** [comment]
You are welcome to submit a PR.

**Comment by henrist** [comment]
Great! I'll see what I can come up with in the near future!

**Comment by moltar** [comment]
That would be awesome! :+1:

**Comment by hupe1980** [comment]
@moltar @henrist You can also try to use propertyMatchers:

```typescript
expect(stack).toMatchCdkSnapshot({
    propertyMatchers: {
      Parameters: expect.any(Object),
      Resources: {
        lambdaFunction1CD98582: {
          Properties: {
            Code: expect.any(Object),
          },
        },
    }
});

```
